accounts/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='accounts'


urlpatterns = [
    path('signup',views.signup ,name='signup'),
    path('check_email_availability/', views.check_email_availability, name='check_email_availability'),
    path('signin',views.signin ,name='signin'),
    path('activate_account/<uidb64>/<token>/', views.activate_account, name='activate'),
    path('log_out',views.log_out ,name='log_out'),
    path('profile/<slug:slug>',views.profile ,name='profile'),
    path('profile/<slug:slug>/order',views.order ,name='order'),
    path('profile/<slug:slug>/order/<int:pk>/detail',views.order_details ,name='order_details'),
    path('productfavorites/<str:slug>',views.product_favorites ,name='product_favorites'),
    path('profile/<slug:slug>/product-favorites',views.showproduct_favorites ,name='showproduct_favorites'),
    path('profile/<slug:slug>/editprofile',views.edit_profile ,name='edit'),
]

orders/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import ajax_check_coupon
app_name='orders'


urlpatterns = [
    path('add_to_cart' , views.add_to_cart , name='add_to_cart'),
    path('cart' , views.cart , name='cart'),
    path('discount_value' , views.discount_value , name='discount_value'),
    path('ajax/check-coupon/', ajax_check_coupon, name='ajax_check_coupon'),
    path('remove_from_Cart/<int:orderdetials_id>' , views.remove_from_Cart , name='remove_from_Cart'),
    path('clear_Cart' , views.clear_Cart , name='clear_Cart'),
    path('add_qty/<int:orderdetials_id>' , views.add_qty , name='add_qty'),
    path('sub_qty/<int:orderdetials_id>' , views.sub_qty , name='sub_qty'),
    # path('payment' , views.ckeck_out , name='ckeck_out'),
    path('payment' , views.paypal_pament , name='paypal_pament'),
    path('order_completed' , views.order_completed , name='order_completed'),
]

product/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='product'


urlpatterns = [
    path('',views.product_list,name='product_list'),
    path('<str:slug>',views.product_detail,name='product_detail')
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('products.urls' ,namespace='products')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls' ,namespace='orders')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
from decimal import Decimal
from audioop import reverse
from django.utils.translation import gettext_lazy as _
from datetime import datetime

from creditcards.models import CardNumberField,CardExpiryField,SecurityCodeField

class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    status = models.CharField(max_length=20,choices=(('تم الشحن', 'تم الشحن'), ('جاري الشحن', 'جاري الشحن')),default='جاري الشحن',)
    coupon=models.ForeignKey('Discount_Coupon', verbose_name=_("Discount Coupon"), on_delete=models.SET_NULL,default=None, null=True, blank=True)
    order_date= models.DateTimeField(verbose_name=_("Created At"), default=datetime.now)
    is_finished = models.BooleanField()
    all_total=models.IntegerField(default=0,verbose_name=_("Total"))
    
    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    def __str__(self):
        return 'User: ' +  self.user.username + ', Order id: ' + str(self.id) + ', status : ' + self.status

    def get_absolute_url(self):
        return reverse("Order_detail", kwargs={"pk": self.pk})
    def get_discount_value(self):
        if self.coupon:
            return self.coupon.discount_value
        return 0
    def update_total(self):
        total = sum(order_detail.total for order_detail in self.orderdetails_set.all())
        self.all_total = total
        self.all_total = self.all_total - self.get_discount_value()
        self.save()

class OrderDetails(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    order = models.ForeignKey(Order,on_delete=models.CASCADE,related_name='orderdetails_set')
    cost=models.DecimalField(max_digits=5,decimal_places=0,verbose_name=_("Cost"))
    quantity=models.IntegerField()
    total=models.IntegerField(default=0)
    
    @property
    def TotalValue(self):
        if self.cost is not None and self.quantity is not None:
            return self.cost * Decimal(self.quantity)
        return 0
    def save(self, *args, **kwargs):
        try:
            product = self.product
            self.cost = product.PRDCost
            
        except Product.DoesNotExist:
            pass
        self.total = self.TotalValue
        super(OrderDetails, self).save(*args, **kwargs)
        self.order.update_total()
    def delete(self, *args, **kwargs):
        super(OrderDetails, self).delete(*args, **kwargs)
        
        # Call the update_total method of the related Order
        self.order.update_total()

    class Meta:
        verbose_name = _("OrderDetails")
        verbose_name_plural = _("OrderDetailss")
    def __str__(self):
        return 'User: ' +  self.order.user.username + 'Product: '+ self.product.PRDname + 'Order id: ' + str(self.order.id)
    def get_absolute_url(self):
        return reverse("OrderDetails_detail", kwargs={"pk": self.pk})

class Discount_Coupon(models.Model):
    user=models.ForeignKey(User, verbose_name=_("user"), on_delete=models.CASCADE)
    name_coupon=models.CharField(max_length=10,verbose_name=_("coupon"))
    discount_value=models.IntegerField()
    class Meta:
        verbose_name = _("Discount Coupon")
        verbose_name_plural = _("Discount Coupons")
    def __str__(self):
        return 'User : ' +  self.user.username + ' , discount value : ' + str(self.discount_value) + ' , name coupon : ' + str(self.name_coupon) + ' , coupon id : ' + str(self.id)

class Checkout(models.Model):
    """Model definition for Checkout."""
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    country=models.CharField(max_length=100)
    adress=models.CharField(max_length=100)
    phone=models.CharField(max_length=20,verbose_name=_("phone"))
    cardholder=models.CharField(max_length=20,verbose_name=_("Card Holder"))
    cardnumber=CardNumberField(verbose_name=_("Card Number"),max_length=16)
    expire=CardExpiryField(verbose_name=_("Exepire Date"))
    security=SecurityCodeField(verbose_name=_("CCV"))
    order_delivery_date= models.DateTimeField(verbose_name=_("Delivery Date"),blank=True, null=True)

    def __str__(self):
        return 'User: ' +  self.order.user.username + ' --> Order id: ' + str(self.id)
    
    class Meta:
        verbose_name = 'Payment'
        verbose_name_plural = 'Payments'
        

orders/views.py
import json
from django.shortcuts import render ,redirect
from django.contrib import messages
from products.models import Product
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseForbidden
from accounts.models import Profile
from.models import *
from django.http import JsonResponse

@login_required(login_url='/accounts/signin')
def add_to_cart(request):
    if request.user.is_authenticated:
        if 'product' in request.GET and  'product_price' in request.GET and  'qty' in request.GET:
            product= request.GET['product']
            qty= request.GET['qty']
            order= Order.objects.all().filter(user=request.user,is_finished=False)
            productname=Product.objects.get(slug=product)
            if order:
                old_order=Order.objects.get(user=request.user,is_finished=False)
                if OrderDetails.objects.all().filter(order=old_order,product=productname).exists():
                    order_detials=OrderDetails.objects.get(order=old_order,product=productname)
                    order_detials.quantity += int(qty)
                    order_detials.save()
                else:
                    order_detials=OrderDetails.objects.create(
                        product=productname,
                        order=old_order,
                        cost=productname.PRDCost,
                        quantity=qty)
            else:
                new_order=Order()
                new_order.user=request.user
                new_order.order_date=timezone.now()
                new_order.is_finished=False
                new_order.save()
                order_detials=OrderDetails.objects.create(
                    product=productname,
                    order=new_order,
                    cost=productname.PRDCost,
                    quantity=qty)
            messages.success(request,'Product added successfully To Cart')
            return redirect ('/' + request.GET['product'])
        else:
            messages.error(request,'Error To Add in Cart')
            return redirect ('/' + request.GET['product'])
    else:
    
        messages.error(request,'You Must Be Login')
        return redirect ('/' + request.GET['product'])

@login_required(login_url='/accounts/signin')
def cart(request):
    context=None
    if Order.objects.all().filter(user=request.user,is_finished=False):
        order=Order.objects.get(user=request.user,is_finished=False)
        orderdetials=OrderDetails.objects.all().filter(order=order)
        total=0
        for sub in orderdetials:
            total += sub.cost * sub.quantity
        context={
            'order':order,
            'orderdetials':orderdetials,
            'total':total,
        }
    return render(request,'order/cart.html', context)

@login_required(login_url='/accounts/signin')
def remove_from_Cart(request,orderdetials_id):
    orderdetials=OrderDetails.objects.get(id=orderdetials_id)
    if request.user.id == orderdetials.order.user.id:
        orderdetials.delete()
        return redirect('/orders/cart')
    else:
        return HttpResponseForbidden("You don't have permission to edit this cart .")

@login_required(login_url='/accounts/signin')
def clear_Cart(request):
    order=Order.objects.get(user=request.user)
    OrderDetails.objects.all().filter(order=order).delete()
    return redirect('/orders/cart')

def discount_value(request):
    if request.method == 'POST':
        front_value = request.POST['discount_value']
        try:
            discount_coupon = Discount_Coupon.objects.get(name_coupon=front_value)
        except Discount_Coupon.DoesNotExist:
            discount_coupon = None
        if discount_coupon:
            orders = Order.objects.filter(user=request.user)  # Get orders for the current user
            for order in orders:
                if order.coupon is None:
                    # Subtract the discount value from the all_total field
                    order.all_total -= discount_coupon.discount_value
                    order.coupon=discount_coupon
                    order.save()
        return redirect('/orders/cart')

def ajax_check_coupon(request):
    coupon_value = request.GET.get("coupon_value")
    order_id = request.GET.get("order_id")
    response_data = {}
    try:
        discount_coupon = Discount_Coupon.objects.get(name_coupon=coupon_value)
        orders = Order.objects.filter(user=request.user)
        for order in orders:
            if order.coupon is None:
                response_data["message"] = "Valid coupon."
                response_data["success"] = True
            else:
                response_data["message"] = "Coupon already used for this order."
                response_data["success"] = False
    except Discount_Coupon.DoesNotExist:
        response_data["message"] = "Invalid coupon."
        response_data["success"] = False
    return JsonResponse(response_data)

def add_qty(request,orderdetials_id):
    if orderdetials_id:
        orderdetials=OrderDetails.objects.get(id=orderdetials_id)
        orderdetials.quantity +=1
        orderdetials.save()
    return redirect('/orders/cart')
def sub_qty(request,orderdetials_id):
    if orderdetials_id:
        orderdetials=OrderDetails.objects.get(id=orderdetials_id)
        if orderdetials.quantity > 1:
            orderdetials.quantity -=1
            orderdetials.save()
    return redirect('/orders/cart')

def paypal_pament(request):
    context=None
    if Order.objects.all().filter(user=request.user,is_finished=False):
        order=Order.objects.get(user=request.user,is_finished=False)
        context={
            'order':order,
        }
    return render(request,'order/paypal.html',context)

def order_completed(request):
    body=json.loads(request.body)
    order=Order.objects.get(user=request.user,is_finished=False,id=body['order_id'])
    order.is_finished = True
    order.save()

def ckeck_out(request):
    context=None
    user_profile=Profile.objects.get(user=request.user)
    cardholder=None
    cardnumber=None
    expire=None
    security=None
    if request.method=='POST' and 'cardnumber' in request.POST and 'cardholder' in request.POST and 'security' in request.POST and 'expire' in request.POST:

        cardholder=request.POST['cardholder']
        cardnumber=request.POST['cardnumber']
        expire=request.POST['expire']
        security=request.POST['security']
        if Order.objects.all().filter(user=request.user,is_finished=False):
            order=Order.objects.get(user=request.user,is_finished=False)
            checkout=Checkout(order=order,
                            country=user_profile.country.name,
                            adress=user_profile.adress,
                            phone=user_profile.phone,
                            cardholder=cardholder,
                            cardnumber=cardnumber,
                            expire=expire,
                            security=security)
            checkout.save()
            order.is_finished=True
            order.save()
            return redirect('/')
    else:
        if Order.objects.all().filter(user=request.user,is_finished=False):
            order=Order.objects.get(user=request.user,is_finished=False)
            orderdetials=OrderDetails.objects.all().filter(order=order)
            total=0
            for sub in orderdetials:
                total += sub.cost * sub.quantity
            context={
                'order':order,
                'orderdetials':orderdetials,
                'total':total,
            }
    return render(request,'order/checkout.html',context)

orders/templates/order/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/about_me.css' %}">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'https://code.jquery.com/jquery-3.6.0.min.js' %}"></script>
</head>
<body dir="rtl">
    <div id="container">
        <nav id="nav"></nav>
        <main id="cart-orders-main">
            <div id="sitbar">
                <div id="person-name">
                    <div id="coupon-validation-message"></div>
                </div>
                <div id="person-name">
                    <h2>الاجمالي</h2>
                    <p style="text-align: center;">{{order.all_total}} $</p>
                    <p style="display: none;" name="order_id" value="{{order.id}}">{{order.id}}</p>
                </div>
                <hr>
                <div style="display: flex;" class="icon-sitbar">
                    <h4 style="width: 50%;font-size: 18px;">رقم الاوردر</h4>
                    <p style="text-align: center;font-weight: 900;">{{order.id}}</p>
                </div>
                <div style="display: flex;" class="icon-sitbar">
                    <h4 style="width: 50%;font-size: 18px;">عدد المنتجات </h4>
                    <p style="text-align: center;font-weight: 900;">{{orderdetials.count}}</p>
                </div>
                <div style="display: flex;" class="icon-sitbar buy-porducts">
                    <form method="POST" action="{% url 'orders:discount_value' %}" style="display: flex;">
                        {% csrf_token %}
                        <input id="inp-text" type="text" style="border: 2px solid rgb(122 122 122);
                        border-radius: 10px;
                        text-align: center;" name="discount_value" placeholder="اضاف كوبون">
                        <button style="border: none;
                        font-size: 20px;
                        padding: 8px;border-radius: 10px;
                        " id="inp-sub" type="submit">اضافه</button>
                    </form>
                </div>
                <div style="display: flex;" class="icon-sitbar buy-porducts">
                    <p style="width: 50%;
                    font-size: 18px;">رسوم التوصيل</p>
                    <p>20$ عند التوصيل</p>
                </div>
                <div style="display: flex;" class="icon-sitbar buy-porducts">
                    <a style="    width: 100%;
                    background-color: rgb(122 122 122);
                    color: white;
                    height: 40px;
                    border: none;
                    border-radius: 7px;
                    font-size: 19px;
                    text-align: center;
                    padding-top: 10px;
                    cursor: pointer;" href="{% url 'orders:paypal_pament'%}">اتمام الشراء</a>
                </div>
                <hr>
                <a style="text-align: center;" id="login-out" href="/">
                    <p> الصفحة الرئيسية </p>
                </a>
            </div>
            <div id="cart-orders">
                {% if orderdetials %}
                    {% for detail in orderdetials  %}
                        <div class="product-card">
                            <div class="img-div">
                                {% if detail.product.PRDIImage %}
                                    <img style="height: 200px;width: 200px;" 
                                    src="{{detail.product.PRDIImage.url}}" alt="">
                                {% else %}
                                    <img style="height: 200px;width: 200px;" 
                                    src="{% static 'img/not_found_image.jpg' %}" alt="">
                                {% endif %}
                            </div>
                            <div class="name-div">
                                <h2>{{detail.product.PRDname}}</h2>
                                <h2>{{detail.total}}</h2>
                                
                            </div>
                            <div class="text-div">
                                <p>
                                    
                                    {{detail.product.PRDDesc}}
                                </p>
                            </div>
                            <div class="but-div">
                                <div>
                                    <button class="like-product"> <img src="{% static 'assets/icon/wishlist.svg' %}" alt="#"> اضاف الى المفضله </button>
                                    <a href="{% url 'orders:remove_from_Cart' orderdetials_id=detail.id %}"
                                        class="remove-product"> 
                                        <img src="{% static 'assets/icon/trash.svg' %}" alt="#"> ازاله </a>
                                </div>
                                <div class="counter" style="display: flex;">
                                    <a href="{% url 'orders:sub_qty' orderdetials_id=detail.id %}" class="minus mr-3 btn btn-outline-success-modify
                                    text-uppercase fw-bold">-</a>
                                    <label class="quantity fw-bold text-black"
                                    style="font-size: 24px;
                                    font-weight: 500;
                                    text-align: center;margin-right: 10px;
                                    margin-left: 10px;" name="qty" >{{detail.quantity}}</label>
                                    <a href="{% url 'orders:add_qty' orderdetials_id=detail.id %}" class="plus ml-3 btn btn-outline-success-modify
                                    text-uppercase fw-bold">+</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                <h4 style="margin: auto; margin-top:50px;margin-bottom:50px;" class="alert alert-warning">There are no purchases here,
                    <a class=" btn ml-2 btn-outline-success-modify"
                    style="text-decoration: none; border: 1px solid #00dcff;"
                    href="{% url 'products:product_list' %}"> All Products</a></h4>
                {% endif %}
            </div>

        </main>
        <!-- <footer id="footer">

        </footer> -->
        <style>
            .plus,
            .minus{
                border: 1px solid #1687d9;
                border-radius: 50%;
                width: 25px;
                height: 25px;
                background-color: #1687d9;
                color: aliceblue;
                font-weight: 900;
                display: flex;
                justify-content: center;
                padding: 0;
            }
        </style>
        <script>
            

            
            $(document).ready(function () {
                $("#inp-text").on("input", function () {
                    var couponValue = $(this).val();
                    if (couponValue.trim() === "") {
                        $("#coupon-validation-message").empty();
                        return;
                    }
                    $.ajax({
                        type: "GET",
                        url: "{% url 'orders:ajax_check_coupon' %}",
                        data: { coupon_value: couponValue },
                        success: function (response) {
                            var messageDiv = $("#coupon-validation-message");
                            if (response.message) {
                                messageDiv.html(response.message);
                                if (response.success) {
                                    messageDiv.css("background-color", "#d4edda");
                                    messageDiv.css("color", "#155724");
                                    messageDiv.css("padding", "5px");
                                    messageDiv.css("text-align", "center");
                                } else {
                                    messageDiv.css("background-color", "#f8d7da");
                                    messageDiv.css("color", "#721c24");
                                    messageDiv.css("padding", "5px");
                                    messageDiv.css("text-align", "center");
                                }
                            } else {
                                messageDiv.empty();
                            }
                        },
                    });
                });
            });
        </script>
    </div>
</body>
</html>

orders/templates/order/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block title %}SOUQ > checkout{% endblock %}
{% block body %}
<head>
    <link rel="stylesheet" href="{% static 'css/checkout.css' %}">
</head>
<body>


  <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins" style="width: 32%; margin: 0 auto">
    <div class="wrapper wrapper--w680">
        <div class="card card-4" style="margin-top: 40px;">
          <div class="Header">
              <a class="arrow-leftt" href="{% url 'orders:cart' %}"><i class="fa-sharp fa-solid fa-arrow-left"></i></a>
              <h3 class="Heading ml-5 text-center" style="color: #1687d9;">CheckOut</h3>
          </div>
          <div class="card-body">
            <div class='text-center mb-3'>
              <i class="fab fa-cc-visa fa-3x mr-3"></i>
              <i class="fab fa-cc-mastercard fa-3x mr-3"></i>
              <i class="fab fa-cc-amex fa-3x mr-3"></i>
              <i class="fab fa-cc-discover fa-3x mr-3"></i>
            </div>
        <form class="form" method="POST" autocomplete="off" novalidate>
          {% csrf_token %}
          <fieldset style="padding-bottom: 0;">
            <label for="card-number" class="text-center" style="color: #1687d9;">User Info</label>
            <hr style="width:10%;margin-bottom:6px;margin-top:8px;"
            {% if user.first_name %}
              <h6>Name : {{user.first_name}} {{user.last_name}} </h6>
            {% else %}
            <h6 style="padding-bottom: 5px;" class="alert alert-danger">Name : You must be go to profile to add this . <a href="{% url 'accounts:edit' slug=user.profile.slug%}" class="btn mt-2 btn-outline-success-modify">Click Here</a></h6>
            {% endif %}
            {% if user.profile.phone %}
              <h6>Phone : {{user.profile.phone}} </h6>
            {% else %}
            <h6 style="padding-bottom: 5px;" class="alert alert-danger">Phone : You must be go to profile to add this . <a href="{% url 'accounts:edit' slug=user.profile.slug%}" class="btn mt-2 btn-outline-success-modify">Click Here</a></h6>
            {% endif %}
            {% if user.email %}
              <h6>Email : {{user.email}} </h6>
            {% else %}
            <h6 style="padding-bottom: 5px;" class="alert alert-danger">Email : You must be go to profile to add this . <a href="{% url 'accounts:edit' slug=user.profile.slug%}" class="btn mt-2 btn-outline-success-modify">Click Here</a></h6>
            {% endif %}
            {% if user.profile.country %}
              <h6>Country : {{user.profile.country.name}} </h6>
            {% else %}
            <h6 style="padding-bottom: 5px;" class="alert alert-danger">Country : You must be go to profile to add this . <a href="{% url 'accounts:edit' slug=user.profile.slug%}" class="btn mt-2 btn-outline-success-modify">Click Here</a></h6>
            {% endif %}
            {% if user.profile.adress %}
              <h6>city : {{user.profile.adress}} </h6>
            {% else %}
            <h6 style="padding-bottom: 5px;" class="alert alert-danger">City : You must be go to profile to add this . <a href="{% url 'accounts:edit' slug=user.profile.slug%}" class="btn mt-2 btn-outline-success-modify">Click Here</a></h6>
            {% endif %}
          </fieldset>
          <hr style="margin-bottom:0;">
          <fieldset style="padding-bottom: 0;">
            <label for="card-number" class="text-center" style="color: #1687d9;">Order Info <hr style="width:10%;margin-bottom:0;"></label>
            <h6>Order Number : {{order.id}}</h6>
            <h6>{{orderdetials.count}} items</h6>
            <h6>Total : {{total}} $</h6>
          </fieldset>
          <fieldset style="padding-bottom: 0;padding-top: 0;">
            <label for="card-number" class="text-center" style="color: #1687d9;">Card Info <hr style="width:10%;margin-bottom:0;"></label>
            <div class="col-12" style="display: flex; gap: 110px;padding: 0;">
              <label for="card-number" style="color: #1687d9;">Card Number</label>
              <label for="card-holder" style="color: #1687d9;">Card holder</label>
            </div>
            <div class="col-12" style="padding: 0;">
              <input type="num" name="cardnumber" id="card-number" class="input-cart-number" style="width: 50%;" placeholder="1111-2222-3333-4444" maxlength="16" />
              <input type="text" name="cardholder"  style="width: 45%;" id="card-holder" />
            </div>
          </fieldset>
          <fieldset style="padding-top: 0;" class="fieldset-expiration">
            <label for="card-expiration-month" style="color: #1687d9;">Expiration date</label>
            <div class="col-12" style="
            display: flex;
            padding-left:0">
              <input placeholder="month / year" name="expire" class="mr-4" style="text-transform:uppercase;"
              type="text"/>
            </div>
          </fieldset>
          <fieldset style="padding-top: 0;" class="fieldset-ccv">
            <label for="card-ccv" style="color: #1687d9;">CCV</label>
            <input type="text" name="security" id="card-ccv" maxlength="3" />
          </fieldset>
          {% if user.first_name and user.email and user.profile.phone and user.profile.country and user.profile.adress  %}
            <button type="submit" href="{% url 'orders:ckeck_out' %}"
              class="btn btn-outline-success-modify
              btn-login text-uppercase fw-bold" style="border-radius: 20px; width:100%;
              justify-content: center;height: 28px;padding: 4px;">Check out</button>
          {% else %}
          {% endif %}
        </form>
          </div>
        </div>
    </div>
  </div>
    <script src="{% static 'js/checkout.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

</body>
  <style>
    body{
      background: linear-gradient(to right, #0062E6, #33AEFF);
    }
    .navbar{
      display: none;
    }
    .arrow-leftt{
      display: flex;
      position: absolute;
      margin-top: 5px;
      margin-left: 5px;
      background-color: #0062E6;
      color: aliceblue;
      height: 25px;
      width: 25px;
      padding: 5px;
      border-radius: 50%;
    }
    .arrow-leftt:hover{
      color: aliceblue;
      text-decoration: none;
    }
  </style>
{% endblock body %}