accounts/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='accounts'


urlpatterns = [
    path('signup',views.signup ,name='signup'),
    path('check_email_availability/', views.check_email_availability, name='check_email_availability'),
    path('signin',views.signin ,name='signin'),
    path('activate_account/<uidb64>/<token>/', views.activate_account, name='activate'),
    path('log_out',views.log_out ,name='log_out'),
    path('profile/<slug:slug>',views.profile ,name='profile'),
    path('profile/<slug:slug>/order',views.order ,name='order'),
    path('profile/<slug:slug>/order/<int:pk>/detail',views.order_details ,name='order_details'),
    path('productfavorites/<str:slug>',views.product_favorites ,name='product_favorites'),
    path('profile/<slug:slug>/product-favorites',views.showproduct_favorites ,name='showproduct_favorites'),
    path('profile/<slug:slug>/editprofile',views.edit_profile ,name='edit'),
]

orders/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import ajax_check_coupon
app_name='orders'


urlpatterns = [
    path('add_to_cart' , views.add_to_cart , name='add_to_cart'),
    path('cart' , views.cart , name='cart'),
    path('discount_value' , views.discount_value , name='discount_value'),
    path('ajax/check-coupon/', ajax_check_coupon, name='ajax_check_coupon'),
    path('remove_from_Cart/<int:orderdetials_id>' , views.remove_from_Cart , name='remove_from_Cart'),
    path('clear_Cart' , views.clear_Cart , name='clear_Cart'),
    path('add_qty/<int:orderdetials_id>' , views.add_qty , name='add_qty'),
    path('sub_qty/<int:orderdetials_id>' , views.sub_qty , name='sub_qty'),
    # path('payment' , views.ckeck_out , name='ckeck_out'),
    path('payment' , views.paypal_pament , name='paypal_pament'),
    path('order_completed' , views.order_completed , name='order_completed'),
]

product/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='product'


urlpatterns = [
    path('',views.product_list,name='product_list'),
    path('<str:slug>',views.product_detail,name='product_detail')
]

products/urls.py
from unicodedata import name
from django.urls import path ,include
from .views import *
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='products'


urlpatterns = [
    path('',ProdcutListView.as_view(),name='product_list'),
    # path('',views.product_list,name='product_list'),
    path('more/<str:category_name>',ProdcutListView_More.as_view(),name='product_list_more'),
    path('<str:slug>',ProdcutDetailView.as_view(),name='product_detail'),
    
    # api
    # path('property/list',PropertyAPiList.as_view(),name='PropertyAPiList'),
    # path('property/list/<int:pk>',PropertyAPiDetail.as_view(),name='PropertyAPiDetail'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('products.urls' ,namespace='products')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls' ,namespace='orders')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.utils.text import slugify
from datetime import datetime
from django.utils.translation import gettext_lazy as _
# Create your models here.
def image_upload(instance,filename):
    imagename , extension = filename.split(".")
    return "product/%s.%s"%(instance.slug,extension) 

class Product(models.Model):
    PRDname=models.CharField(max_length=100,verbose_name=_("product name"))
    PRDcategory=models.ForeignKey('Category',limit_choices_to={'CATParent__isnull' : False},on_delete=models.CASCADE,blank=True, null=True,verbose_name=("Categery"))
    PRDBrand=models.ForeignKey('settings.Brand',on_delete=models.CASCADE,blank=True, null=True,verbose_name=("Brand"))
    PRDDesc=models.TextField(verbose_name=_("Product Descripton"))
    PRDIImage=models.ImageField(upload_to=image_upload ,verbose_name=("Image"),blank=True, null=True)
    
    
    PRDPrice=models.DecimalField(max_digits=5,decimal_places=0 , verbose_name=_("Price"))
    PRDPriceDiscount=models.DecimalField(max_digits=5,decimal_places=0 , verbose_name=_("discount") ,default='0')
    PRDCost=models.DecimalField(max_digits=5,decimal_places=0,verbose_name=_("Cost"),blank=True,null=True)
    
    
    PRDCreated=models.DateTimeField(verbose_name=_("Created At"), default=datetime.now)
    slug = models.SlugField(blank=True ,null=True)
    PRDIs_Active=models.BooleanField(default=False ,verbose_name=_("Active"))
    PRDNew=models.BooleanField(default=True ,verbose_name=_("New-Product"))
    PRDSeller=models.BooleanField(default=False ,verbose_name=_("Bestseller"))
    
    @property
    def PRDCostValue(self):
        return self.PRDPrice - self.PRDPriceDiscount

    def save(self,*args,**kwargs):
        self.slug= slugify(self.PRDname)
        self.PRDCost = self.PRDCostValue
        super(Product,self).save(*args,**kwargs)
    def __str__(self) -> str:
        return self.PRDname
    
    # def __str__(self) -> str:
    #     return self.PRDNew
    
    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")
        ordering= ['PRDPriceDiscount']
        ordering= ['-PRDNew']
            
            
class ProductImage(models.Model):
    PRDIProduct=models.ForeignKey(Product,on_delete=models.CASCADE ,verbose_name=("product"))
    PRDIImage=models.ImageField(upload_to='product/' ,verbose_name=("Image"))
    def __str__(self) -> str:
        return str(self.PRDIProduct)

class Category(models.Model):
    CATName=models.CharField(max_length=50,verbose_name=("Name"))
    CATParent=models.ForeignKey('self',limit_choices_to={'CATParent__isnull' : True},on_delete=models.CASCADE,blank=True, null=True,verbose_name=("Main Category"))
    CATDes=models.TextField(verbose_name=("Description"))
    CATImg=models.ImageField(upload_to='category',verbose_name=("Images"))
    def __str__(self):
        return self.CATName
    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
    
class Product_ALternative (models.Model):
    PALNProduct=models.ForeignKey(Product ,on_delete=models.CASCADE,related_name='main_product',verbose_name=("Product"))
    PALNAlternatives=models.ManyToManyField(Product,related_name='alternative_product',verbose_name=("Alternative"))
    class Meta:
        verbose_name = _("Product_ALternative")
        verbose_name_plural = _("Product_ALternatives")

    def __str__(self):
        return str(self.PALNProduct)

class Product_Accessories (models.Model):
    PACCProduct=models.ForeignKey(Product ,on_delete=models.CASCADE,related_name='mainAccessory_product',verbose_name=("Product"))
    PACCAlternatives=models.ManyToManyField(Product,related_name='Accessory_product',verbose_name=("Accessory"))

    class Meta:
        verbose_name = _("Product_Accessory")
        verbose_name_plural = _("Product_Accessories")

    def __str__(self):
        return str(self.PACCProduct)

products/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

# Create your models here.
User = get_user_model()
def image_upload(instance,filename):
    imagename , extension = filename.split(".")
    return "product/%s.%s"%(instance.slug,extension) 

class Product(models.Model):
    PRDname=models.CharField(max_length=300,verbose_name=_("product name"))
    PRDIImage=models.ImageField(upload_to=image_upload ,verbose_name=("Image"),blank=True, null=True)
    PRDDesc=models.TextField(verbose_name=_("Product Descripton"))
    
    PRDquantity=models.DecimalField(max_digits=10,decimal_places=0 , verbose_name=_("َQuantity") ,default='0')
    purchasingprice=models.DecimalField(max_digits=10,decimal_places=0,verbose_name=_("Purchasing Price") ,default='0')
    
    PRDcategory=models.ForeignKey('Category',limit_choices_to={'CATParent__isnull' : False},on_delete=models.CASCADE,blank=True, null=True,verbose_name=("Categery"))
    PRDBrand=models.ForeignKey('Brand',on_delete=models.CASCADE,blank=True, null=True,verbose_name=("Brand"))
    
    PRDPrice=models.DecimalField(max_digits=5,decimal_places=0 , verbose_name=_("Price"))
    PRDPriceDiscount=models.DecimalField(max_digits=5,decimal_places=0 , verbose_name=_("discount") ,default='0')
    PRDCost=models.DecimalField(max_digits=5,decimal_places=0,verbose_name=_("Cost"),blank=True,null=True)
    
    
    PRDCreated=models.DateTimeField(verbose_name=_("Created At"), auto_now_add=True)
    slug = models.SlugField(blank=True ,null=True)
    PRDIs_Active=models.BooleanField(default=False ,verbose_name=_("Active"))
    PRDNew=models.BooleanField(default=True ,verbose_name=_("New-Product"))
    PRDSeller=models.BooleanField(default=False ,verbose_name=_("Bestseller"))
    
    @property
    def PRDCostValue(self):
        return self.PRDPrice - self.PRDPriceDiscount

    def save(self,*args,**kwargs):
        self.slug= slugify(self.PRDname)
        self.PRDCost = self.PRDCostValue
        super(Product,self).save(*args,**kwargs)
        
    def __str__(self):
        return self.PRDname
    
    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")
        ordering= ['PRDPriceDiscount']
        ordering= ['-PRDNew']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        
        
class Category(models.Model):
    CATName=models.CharField(max_length=50,verbose_name=("Name"))
    CATParent=models.ForeignKey('self',limit_choices_to={'CATParent__isnull' : True},on_delete=models.CASCADE,blank=True, null=True,verbose_name=("Main Category"))
    CATDes=models.TextField(verbose_name=("Description"))
    CATImg=models.ImageField(upload_to='category',verbose_name=("Images"))
    def __str__(self):
        return self.CATName
    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        
        
        
class Brand(models.Model):
    BRDName=models.CharField(max_length=40,verbose_name=("Name"))
    BRDDesc=models.TextField(blank=True, null=True,verbose_name=("Description"))

    class Meta:
        verbose_name = _("Brand")
        verbose_name_plural = _("Brands")

    def __str__(self):
        return self.BRDName

product/views.py
from django.shortcuts import render
from.models import Product
from django.core.paginator import Paginator

# Create your views here.

def product_list(request):
    product_list=Product.objects.all()
    paginator = Paginator(product_list, 6) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    product_list = paginator.get_page(page_number)
    name = ''
    if 'searchname' in request.GET:
        product_list1=Product.objects.all()
        name = request.GET['searchname']
        if name:
            product_list = product_list1.filter(PRDname__icontains=name)
    context ={'product_list' : product_list}
    return render(request, 'Product/product_list.html',context)
    
def product_detail(request,slug):
    product_detail = Product.objects.get(slug=slug)
    context ={'product_detail' : product_detail}
    return render(request, 'Product/product_detail.html',context)

products/views.py
from django.shortcuts import render
from django.views.generic import ListView ,DetailView ,CreateView
from django.contrib.auth.models import User
from.models import *
from django.views.generic.edit import FormMixin
from django.core.exceptions import ValidationError
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from settings.models import Nav_ads
# Create your views here.


# class ProdcutListView(ListView):
#     model = Product
#     template_name = "product_list.html"
#     context_object_name='product_list'
#     def get_context_data(self, **kwargs):
#         context =super().get_context_data(**kwargs)
#         distinct_categories = context['product_list'].values_list('PRDcategory__CATName', flat=True).distinct()
#         context['category'] = distinct_categories
#         nav_img = Nav_ads.objects.all()
#         context['nav_img'] = nav_img
#         return context

class ProdcutListView(ListView):
    model = Product
    template_name = "products/product_list.html"
    context_object_name = 'category_product_map'

    def get_queryset(self):
        categories = Category.objects.exclude(
            CATParent=None
        ).filter(
            CATParent__isnull=False,
            product__PRDIs_Active=True
        )
        
        category_product_map = {}
        for category in categories:
            products = Product.objects.filter(PRDcategory=category, PRDIs_Active=True)[:12]
            category_product_map[category.CATName] = products
        
        return category_product_map

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        nav_img = Nav_ads.objects.all()
        context['nav_img'] = nav_img
        return context


# def product_list(request):
#     categories = Category.objects.exclude(CATParent=None).filter(CATParent__isnull=False,product__PRDIs_Active=True)
    
#     category_product_map = {}
#     for category in categories:
#         products = Product.objects.filter(PRDcategory=category, PRDIs_Active=True)[:12]
#         category_product_map[category.CATName] = products
    
#     context = {'category_product_map': category_product_map}
#     return render(request, 'products/product_list.html', context)

class ProdcutDetailView(DetailView):
    model = Product
    # template_name = "product_detail.html"
    context_object_name='product_detail'

class ProdcutListView_More(ListView):
    model = Product
    template_name = "products/product_list_more.html"
    context_object_name='product_list_more'
    paginate_by=18
    def get_queryset(self):
        category_name = self.kwargs.get('category_name')
        category = get_object_or_404(Category, CATName=category_name)
        products_in_category = Product.objects.filter(PRDcategory=category, PRDIs_Active=True)
        return products_in_category
    
    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        distinct_categories = Category.objects.filter(
            product__in=context['product_list_more']
        ).distinct()
        context['category'] = distinct_categories
        return context

product/templates/product/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    SOUQ > {{product_detail.slug}}
{% endblock %}
{% block body %}
    <main class="mt-5 pt-4">
        <div class="container dark-grey-text mt-5">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success" role="alert">{{message}}</div>
                {% endfor %}
            {% endif %}
            <div class="row">
                <div class="col-md-6 mb-5 project-imagee">
                    {% if product_detail.PRDPriceDiscount > 0  %}
                        <a href="" style="text-decoration: none ;position: absolute;transform:rotate(-35deg)">
                            <span class="badge red mr-5 mt-2">Price offer</span>
                        </a>
                    {% else %}
                                    
                    {% endif %}
                    {% if product_detail.PRDIImage  %}
                        <img src="{{product_detail.PRDIImage.url}}" class="card-img-top" alt="...">
                    {% else %}
                        <img src="{%static 'img/not_found_image.jpg'%}" class="card-img-top" alt="...">
                    {% endif %} 
                </div>
                <div class="col-md-6 mb-4">
                    <div class="p-4 ml-5">
                        <div class="mb-3">
                        <a href="" style="text-decoration: none">
                            <span class="badge purple mr-1">{{product_detail.PRDcategory}}</span>
                        </a>
                        
                        {% if product_detail.PRDNew %}
                            <a href="" style="text-decoration: none">
                                <span class="badge blue mr-1">New</span>
                            </a>
                        {% endif %}
                        {% if product_detail.PRDSeller %}
                            <a href="" style="text-decoration: none">
                                <span class="badge red mr-1">Bestseller</span>
                            </a>
                        {% endif %}
                    </div>
                        
                        <p class="lead">
                            {% if product_detail.PRDPriceDiscount > 0  %}
                                <span class="mr-1">
                                    <del>{{product_detail.PRDPrice}} $</del>
                                </span>
                                <span>{{product_detail.PRDCost}}$</span>
                            {% else %}
                                <span>{{product_detail.PRDPrice}}$</span>
                            {% endif %}
                        </p>
                        <h1 class="font-weight-bold">{{product_detail}}</h1>
                        <p class="lead font-weight-bold">Description</p>
                        <p>{{product_detail.PRDDesc}}</p>

                        <form id="formaddtocart" class="d-flex justify-content-left" action="{% url 'orders:add_to_cart' %}">
                        <button type="button" class="btn btn ml-2 btn-outline-success-modify my-2 my-sm-0" data-toggle="modal" data-target="#staticBackdrop">
                            Add to cart <i class="fas fa-shopping-cart ml-1"></i>
                        </button>
                        <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel">Add To Cart</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="col-12">
                                            <div class="input-group">
                                                <label class="label">Quantity : </label>
                                                <input class="input--style-4" type="number" name="qty" value="1" >
                                                <input type="hidden" name="product" value="{{product_detail.slug}}">
                                                <input type="hidden" name="product_price" value="{{product_detail.PRDCost}}">
                                            </div> 
                                        </div>
                                        <!-- <div class="col-6">
                                            <div class="input-group" style="border-radius: 25%;
                                            border: 2px solid #2196f3;
                                            padding: 7px;
                                            width: 80%;
                                            color: #2196f3;">
                                                <label class="label">Total Price : </label>
                                                <label class="label ml-3"> {{product_detail.PRDCost}} $</label>
                                                
                                            </div>
                                        </div> -->
                                    </div>
                                    <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" id="btmclose" data-dismiss="modal">Close</button>
                                    <button class="btn ml-2 btn-outline-success-modify my-2 my-sm-0" onclick="addtocart()" type="button">Add To Cart</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'accounts:product_favorites' slug=product_detail.slug %}" class="btn ml-2 btn-outline-success-modify my-2 my-sm-0" type="favorite">
                            <i class="fa-regular fa-heart" style="font-size: 20px;"></i>
                        </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <hr>
    <div class="container mb-5">
            <div class="row">
                <div class="modfiy-center mb-3">
                    <h6>Leave Your Review</h6>
                </div>
            </div> 
            <div class="form-group">
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Leave your review"></textarea>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                <label class="form-check-label" for="inlineRadio1"><i class="fa-regular fa-star"></i></label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                <label class="form-check-label" for="inlineRadio2"><i class="fa-solid fa-star"></i></label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                <label class="form-check-label" for="inlineRadio3">3</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                <label class="form-check-label" for="inlineRadio3">4</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                <label class="form-check-label" for="inlineRadio3">5</label>
            </div>
            <br>
            <button class="btn btn-outline-success-modify my-2 my-sm-0"  type="submit">Submit</button>
        </form>
    </div>
    <hr>
    <div class="container mb-5">
        <div class="row">
            <div class="col-md-3 mt-5">

                <img class="review-img" src="{% static 'img/dd.jpg'%}" alt="card-img-top">
            </div>
            <div class="col md-9 mt-5">
                <h3 class="p-3">User Name</h3>
                <p class="p-3">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock . "</p>
            </div>
        </div>
    </div>

    <style>
        input[type=number]{
            width: 100%;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f1f1f1;
        }
        
        input[type=number]:focus {
            background-color: #ddd;
            outline: none;
        }
    </style>
    <script>
        function addtocart(){
            document.getElementById('btmclose').click();
            document.getElementById('formaddtocart').submit();
        }
    </script>
{% endblock body %}
    

product/templates/product/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}SOUQ{% endblock %}
{% block body %}  
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">{{message}}</div>
        {% endfor %}
    {% endif %}
    <div class="container mt-3">
        {{name}}
        <div class="row">
            {% for product in product_list %}
            {% if product.PRDIs_Active  %}
                    <div class="col-lg-3 col-md-6 col-sm-12 mt-3">
                        <div class="card" style="width: 17rem; height:20.5rem;">
                            <div class="project-image">
                                {% if product.PRDIImage  %}
                                    <img src="{{product.PRDIImage.url}}" class="card-img-top" alt="...">
                                {% else %}
                                    <img src="{% static 'img/not_found_image.jpg' %}" class="card-img-top" alt="...">
                                {% endif %}     
                            </div>
                            <div class="card-body">
                                <h4 class="card-title text-center"><a href="{% url 'products:product_detail' product.slug %}" style="color: black ;text-decoration:none">{{product}}</a></h4>
                                <p class="card-text text-center">
                                    {% if product.PRDPriceDiscount > 0  %}
                                        <span class="mr-1">
                                            <del>{{product.PRDPrice}} $</del>
                                        </span>
                                        <span>{{product.PRDCost}}$</span>
                                    {% else %}
                                        <span>{{product.PRDPrice}}$</span>
                                    {% endif %}
                                </p>
                                <p>
                                    {% if product.PRDPriceDiscount > 0  %}
                                        <a href="" style="text-decoration: none ;">
                                            <span class="badge red mr-3 ">Price offer</span>
                                        </a>
                                    {% else %}
                                                
                                    {% endif %}
                                    {% if product.PRDNew %}
                                        <a href="" style="text-decoration: none ;">
                                        <span class="badge badge-pill badge blue mr-3">NEW</span>
                                        </a>
                                    {% endif %}
                                    {% if product.PRDSeller %}
                                        <a href="" style="text-decoration: none">
                                            <span class="badge red badge-pill">Bestseller</span>
                                        </a>
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                {% else %}
                    
                {% endif %}
            
            {% empty %}
                    <h4 style="margin: auto;" class="alert alert-warning"> No Products here ,
                        <a class=" btn ml-2 btn-outline-success-modify" style="text-decoration: none; border: 1px solid #00dcff;" href="{% url 'product:product_list' %}"> All Products</a></h4>
            {% endfor %}
        </div>
    </div>
    <div class="container mt-5">
        {% if product_list.has_other_pages %}
            <div class="row">
                <div class="all_products_pagination">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            {% if product_list.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{product_list.previous_page_number}}">Previous</a></li>
                            {% endif %}
                            {% for i in product_list.paginator.page_range %}
                                <li class="page-item"><a class="page-link" href="?page={{i}}"><span>{{i}}</span></a></li>
                            {% endfor %}
                            {% if product_list.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{product_list.next_page_number}}">Next</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock body %}