accounts/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='accounts'


urlpatterns = [
    path('signup',views.signup ,name='signup'),
    path('check_email_availability/', views.check_email_availability, name='check_email_availability'),
    path('signin',views.signin ,name='signin'),
    path('activate_account/<uidb64>/<token>/', views.activate_account, name='activate'),
    path('log_out',views.log_out ,name='log_out'),
    path('profile/<slug:slug>',views.profile ,name='profile'),
    path('profile/<slug:slug>/order',views.order ,name='order'),
    path('profile/<slug:slug>/order/<int:pk>/detail',views.order_details ,name='order_details'),
    path('productfavorites/<str:slug>',views.product_favorites ,name='product_favorites'),
    path('profile/<slug:slug>/product-favorites',views.showproduct_favorites ,name='showproduct_favorites'),
    path('profile/<slug:slug>/editprofile',views.edit_profile ,name='edit'),
]

orders/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import ajax_check_coupon
app_name='orders'


urlpatterns = [
    path('add_to_cart' , views.add_to_cart , name='add_to_cart'),
    path('cart' , views.cart , name='cart'),
    path('discount_value' , views.discount_value , name='discount_value'),
    path('ajax/check-coupon/', ajax_check_coupon, name='ajax_check_coupon'),
    path('remove_from_Cart/<int:orderdetials_id>' , views.remove_from_Cart , name='remove_from_Cart'),
    path('clear_Cart' , views.clear_Cart , name='clear_Cart'),
    path('add_qty/<int:orderdetials_id>' , views.add_qty , name='add_qty'),
    path('sub_qty/<int:orderdetials_id>' , views.sub_qty , name='sub_qty'),
    # path('payment' , views.ckeck_out , name='ckeck_out'),
    path('payment' , views.paypal_pament , name='paypal_pament'),
    path('order_completed' , views.order_completed , name='order_completed'),
]

product/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='product'


urlpatterns = [
    path('',views.product_list,name='product_list'),
    path('<str:slug>',views.product_detail,name='product_detail')
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('products.urls' ,namespace='products')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls' ,namespace='orders')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from audioop import reverse
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.utils.translation import gettext_lazy as _
from datetime import datetime
from django_countries.fields import CountryField
from django.utils.text import slugify
from django.db.models.signals import post_save
from products.models import Product
class Profile(models.Model):
    user=models.OneToOneField(User, verbose_name=_("user"), on_delete=models.CASCADE)
    productfavorites=models.ManyToManyField(Product,blank=True,null=True)
    phone=models.CharField(max_length=20,verbose_name=_("phone"))
    image=models.ImageField(upload_to='profile/',blank=True, null=True)
    country=CountryField(blank_label='select country')
    adress=models.CharField(max_length=100)
    join_date=models.DateTimeField(verbose_name=_("Created At"), default=datetime.now)
    slug=models.SlugField(blank=True, null=True) 
    
    def save(self ,*args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")

    def __str__(self):
        return '%s' %(self.user)

    def get_absolute_url(self):
        return reverse("accounts:Profile_detail", kwargs={"slug": self.slug})

    def create_profile(sender ,*args, **kwargs):
        if kwargs['created']:
            user_profile=Profile.objects.create(user=kwargs['instance'])    
    post_save.connect(create_profile , sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username' , 'email','first_name','last_name']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image' , 'country', 'adress']

accounts/views.py
from django.contrib import messages
from django.shortcuts import render ,redirect ,get_object_or_404
from orders.models import Order,OrderDetails
from.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login ,authenticate
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django_countries import countries
from.tokens import accout_actvation_token
from django.core.mail import EmailMessage
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes,force_str
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from project import settings
from django.contrib.auth import logout
from django.http import JsonResponse
from products.models import Product
def activate_account(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and accout_actvation_token.check_token(user, token):
        # activate the user's account
        user.is_active = True
        user.save()
        messages.success(request, 'Your account has been activated!')
        login(request, user)
        return redirect('/')
    else:
        messages.error(request, 'Invalid activation link.')
        return redirect('/')


def signup(request):
    if request.user.is_authenticated:  
        return redirect('/')
    
    if request.method == 'POST':
        first_name=None
        scand_name=None
        email=None
        password=None
        passwordconfigration=None
        
        if 'first_name' in request.POST : first_name=request.POST['first_name']
        else :messages.error(request,'Error in First Name !')
        
        if 'scand_name' in request.POST : scand_name=request.POST['scand_name']
        else :messages.error(request,'Error in Scand Name !')
        
        if 'email' in request.POST : email=request.POST['email']
        else : messages.error(request,'Error in Email !')
        
        if 'password' in request.POST: password=request.POST['password']
        else : messages.error(request,'Error in password !')
        
        if 'passwordconfigration' in request.POST: passwordconfigration=request.POST['passwordconfigration']
        else : messages.error(request,'Error in Password Configration !')
        
        context={'first_name':first_name,
                    'scand_name':scand_name,
                    'email':email}
        if first_name and scand_name and email and password and passwordconfigration:
            if User.objects.filter(email=email).exists():
                messages.error(request,'This Email Name is taken !')
                return render(request,'registration/signup.html',context)
            else:
                if password != passwordconfigration:
                    messages.error(request,'The two password fields didn’t match.')
                    return render(request,'registration/signup.html',context)
                else:
                    username = email.split("@")[0]
                    user = User.objects.create_user(
                    username=username,
                    first_name=first_name,
                    last_name=scand_name,
                    is_active=False,
                    email=email,
                    password=password
                    )
                    user.save()
        else:
            messages.error(request,'Please fill in all fields !')
            return render(request,'registration/signup.html',context)
        mailsubject='activate your account'
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = accout_actvation_token.make_token(user)
        message=f"Hi {user.username},\n\nPlease click on the following link to activate your account:\n\n{get_current_site(request).domain}/accounts/activate_account/{uid}/{token}/\n\nThanks!\n"
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [user.email,] 
        emailmessage=send_mail(mailsubject,message,email_from,recipient_list)
        
        if emailmessage:
            messages.success(request,f'User has been registered successfully , go to {email} to activate your account ! ')
            return redirect('/accounts/signin')
        else:
            messages.error(request,f'filed to send email to  {email} ! ')
            return redirect('/accounts/signup')
    else:
        return render(request,'registration/signup.html')

def check_email_availability(request):
    email = request.GET.get("email")
    response_data = {}
    if User.objects.filter(email=email).exists():
        response_data["available"] = False
    else:
        response_data["available"] = True
    return JsonResponse(response_data)

def signin(request):
    if request.user.is_authenticated:  
        return redirect('/')
    
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, 'Go to'+email+'to active your account !')
                return redirect('/accounts/signin')
        else:
            messages.error(request, 'Invalid email or password')
            return redirect('/accounts/signin')
    else:
        return render(request, 'registration/signin.html')

# def log_out(request):
#     context ={'log_out' : log_out}
#     return render(request, 'registration/logged_out.html',context)

def log_out(request):
    logout(request)
    return redirect('/')

@login_required(login_url='/accounts/login/')
def profile(request,slug):
    profile=get_object_or_404(Profile,slug=slug)
    if request.user.id == profile.user.id:
        context={'profile':profile}
        return render(request,'profile.html',context)
    else:
        return HttpResponseForbidden("You don't have permission to view this profile.")

@login_required(login_url='/accounts/login/')
def edit_profile(request ,slug):
    country_list = list(countries)
    if request.method == 'POST':
        if request.user is not None:
            user_profile = Profile.objects.get(user=request.user)
            context={
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
                'email': request.user.email,
                'phone': user_profile.phone,
                'country': user_profile.country,
                'country_list': country_list,
                'adress': user_profile.adress,
            }
            if request.POST['first_name'] and request.POST['last_name'] and request.POST['email'] and request.POST['phone'] and request.POST['country']  and request.POST['adress']:
                request.user.first_name= request.POST['first_name']
                request.user.last_name= request.POST['last_name']
                if request.POST['email'] != request.user.email:
                    if User.objects.filter(email=request.POST['email']).exists():
                        messages.error(request, 'Email is already taken.')
                        return render(request, 'editprofile.html', context)
                    request.user.email = request.POST['email']
                user_profile.phone= request.POST['phone']
                if 'country' in request.POST:
                    user_profile.country = request.POST['country']
                user_profile.adress= request.POST['adress']
                request.user.save()
                user_profile.save()
                messages.success(request,'Your Data Has Been Saved')
                context1={
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
                'email': request.user.email,
                'phone': user_profile.phone,
                'country': user_profile.country,
                'country_list': country_list,
                'adress': user_profile.adress,
                }
                slug = user_profile.slug
                return redirect ('/accounts/profile/' +slug+ '/editprofile')
            else:
                messages.error(request,'Please fill in all fields !')
                return render(request, 'editprofile.html',context)
        return render(request, 'editprofile.html',context)
    else:
        if request.user is not None:
            user_profile = Profile.objects.get(user=request.user)
            context={
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
                'email': request.user.email,
                'phone': user_profile.phone,
                'country': user_profile.country,
                'country_list': country_list,
                'adress': user_profile.adress,
            }
        return render(request, 'editprofile.html',context)
    
from operator import itemgetter
def order(request ,slug):
    profile=get_object_or_404(Profile,slug=slug)
    if request.user.id == profile.user.id:
        orders= Order.objects.all().filter(is_finished=True,user=request.user)
        sorted_orders = sorted(orders, key=lambda order: order.status == 'تم الشحن', reverse=True)
        context= {'sorted_orders' : sorted_orders ,}
        return render(request, 'about_me/orders.html',context)
    else:
        return HttpResponseForbidden("You don't have permission to view this profile.")

def order_details(request ,slug,pk):
    profile=get_object_or_404(Profile,slug=slug)
    if request.user.id == profile.user.id:

accounts/templates/editprofile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
        EditProfile 
{% endblock %}
{% block body %}
<head>
    <link rel="stylesheet" href="{% static 'css/editprofile.css' %}">
    <link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
</head>
    <style>
        input[type=text], input[type=username]{
            height: 20px;
        }
        select {
            width: 100%;
            padding: 3px;
            height: 30px;
            padding-left: 10px;
            font-size: 14px;
            border-radius: 5px;
            border: 1px solid gray;
        }
        .upload {
            padding: 9px;
            border-radius: 11px;
            background-color: #007bff;
            border: 1px solid #007bff;
            font-size: 13px;
            font-weight: 400;
            line-height: 1.5;
            color: white;
            cursor: pointer;
            justify-content: center;
            display: flex;
        }
        input[type=email]{
            width: 100%;
            height: 20px;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f1f1f1;
        }
            
        input[type=email]:focus{
            background-color: #ddd;
            outline: none;
        }
        .save-back {
            display: flex;
            height: 36px;
            margin-top: 10px;
            justify-content: space-around;
            text-align: center;
            align-items: center;
        }
    </style>
    <div class="container">
        <h4 class="titttle">Edit your profile</h4>
        {% if messages %}
        <style>
            .titttle{
                margin-bottom: 10px;
            }
        </style>
            {% for message in messages %}
                <div class="alert alert-success" role="alert">{{message}}</div>
            {% endfor %}
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="row row-space">
                <div class="col-6">
                    <img class='profile_img' style="margin-top: 90px;" src="/static/img/profile_img.svg" alt="" width="350px" ,height="350px" >
                </div>
                <div class="col-6">
                    <div class="center">
                        <div>
                            <div style="width: 50%;margin: 0 auto;">
                                <div>
                                    <label class="profile-label"> Profile Image </label><br><br>
                                    {% if profile.image  %}
                                        <img class="profile-img" src="{{profile.image.url}}" name="image" alt="card-img-top">
                                    {% else %}
                                        <img width="110" height="100" style="margin: 0 auto;
                                        display: flex;width: 200px; height: 200px;"
                                        class = "pimg" name="image" src="{% static 'img/user_no_image.png' %}">
                                    {% endif %}
                                </div>
                                <label class = "upload" style="width: 35%;
                                margin: 0 auto;">
                                select image
                                <input type="file" name="image" value="" style="display: none;" class="form-control file">
                                </label>
                            </div>
                            <div class="row row-space">
                                <div class="col-6">
                                    <div class="input-group">
                                        <label class="label" style="margin: 0 auto;">الاسم الاول</label>
                                        <input class="input--style-4" type="text" name="first_name" value="{{first_name}}">
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="input-group">
                                        <label class="label" style="margin: 0 auto;">الاسم الثانس</label>
                                        <input class="input--style-4" type="text" name="last_name" value="{{last_name}}">
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="input-group">
                                        <label class="label" style="margin: 0 auto;">الايميل</label>
                                        <input class="input--style-4" style="font-size: 13px;" type="email" name="email" value="{{email}}">
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="input-group">
                                        <label class="label" style="margin: 0 auto;">رقم التلفون</label>
                                        <input class="input--style-4" type="text" id="phone" name="phone" value="{{phone}}">
                                    </div>
                                </div>
                                <div class="col-6">
                                    <label for="country">الدولة 
                                        <i class="{{ country.flag_css }}"></i></label>
                                        <select name="country">
                                            {% for code, name in country_list %}
                                                <option value="{{ code }}"
                                                {% if country == code %}
                                                selected="selected"{% endif %}>{{ name }}</option>
                                            {% endfor %}
                                        </select>
                                </div>
                                <div class="col-6">
                                    <div class="input-group">
                                        <label class="label" style="margin: 0 auto;">المدينه</label>
                                        <input class="input--style-4" type="text" name="adress" value="{{adress}}">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="save-back">
                        <button class="upload save" href=""> حفظ </button>
                        <a  class="back btn btn-outline-success-modify" href="{% url 'accounts:profile' slug=user.profile.slug %}" > back </a>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock body %}

accounts/templates/favorite.html
{% extends 'base.html' %}
{% load static %}
{% block title %}SOUQ > Favorite{% endblock %}
{% block body %}  
<div class="container mt-3">
    {{name}}
    <div class="modfiy-center mb-2" style="width: 110px; color: #2196f3;">
        <h4 style="    font-size: 1.5rem;
        border: 2px solid;
        padding: 10px;
        border-radius: 25%;">Favorite</h4>
    </div>
    <div class="row">
        {% for product in product_list %}
        {% if product.PRDIs_Active  %}
                <div class="col-lg-4 col-md-6 col-sm-12 mt-3">
                    <div class="card" style="width: 17rem; height:20.5rem;">
                        <div class="project-image">
                            {% if product.PRDIImage  %}
                                <img src="{{product.PRDIImage.url}}" class="card-img-top" alt="...">
                            {% else %}
                                <img src="{% static 'img/not_found_image.jpg' %}" class="card-img-top" alt="...">
                            {% endif %}     
                        </div>
                        <div class="card-body">
                            <h4 class="card-title text-center"><a href="{% url 'products:product_detail' product.slug %}" style="color: black ;text-decoration:none">{{product}}</a></h4>
                            <p class="card-text text-center">
                                {% if product.PRDPriceDiscount > 0  %}
                                    <span class="mr-1">
                                        <del>{{product.PRDPrice}} $</del>
                                    </span>
                                    <span>{{product.PRDCost}}$</span>
                                {% else %}
                                    <span>{{product.PRDPrice}}$</span>
                                {% endif %}
                            </p>
                            <p>
                                {% if product.PRDPriceDiscount > 0  %}
                                    <a href="" style="text-decoration: none ;">
                                        <span class="badge red mr-3 ">Price offer</span>
                                    </a>
                                {% else %}
                                            
                                {% endif %}
                                {% if product.PRDNew %}
                                    <a href="" style="text-decoration: none ;">
                                    <span class="badge badge-pill badge blue mr-3">NEW</span>
                                    </a>
                                {% endif %}
                                {% if product.PRDSeller %}
                                    <a href="" style="text-decoration: none">
                                        <span class="badge red badge-pill">Bestseller</span>
                                    </a>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
            {% else %}
                
            {% endif %}
        
        {% empty %}
                <h4 style="margin: auto;" class="alert alert-warning"> No Products here ,
                    <a class=" btn ml-2 btn-outline-success-modify" style="text-decoration: none; border: 1px solid #00dcff;" href="{% url 'product:product_list' %}"> All Products</a></h4>
        {% endfor %}
    </div>
</div>
{% endblock body %}

accounts/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/about_me.css' %}">
    <title>Document</title>
</head>
<style>
    .main-container{
        text-align: center;
        align-items: center;
        justify-content: center;
        display: flex;
    }
    h6{
        font-size: 22px;
        margin: 10px;
    }
    .btn {
        cursor: pointer;
        padding: 10px;
        border-radius: 10px;
        box-shadow: none !important;
    }
    .btn-outline-success-modify {
        border-radius: 5px;
        color: #ffffff;
        background-color: #007bff;
        border-color: #007bff;
    }
</style>
<body dir="rtl">
    <div id="container">
        <nav id="nav"></nav>
        <main id="cart-orders-main">
            <div id="sitbar">
                <div id="person-name">
                    <h2> اهلا زياد احمد </h2>
                    <p>ziad0713@gmail.com</p>
                </div>
                <hr>
                <a class="icon-sitbar" href="{% url 'accounts:profile' slug=user.profile.slug %}">
                  <img src="{% static 'assets/icon/account-profile.svg' %}" alt="">
                  <p>حساب</p>
                </a>
                <a class="icon-sitbar" href="{% url 'accounts:order' slug=user.profile.slug %}">
                    <img src="{% static 'assets/icon/account-orders.svg' %}" alt="">
                    <p>الطلبات</p>
                </a>
                <a class="icon-sitbar" href="{% url 'accounts:showproduct_favorites' slug=user.profile.slug %}">
                    <img src="{% static 'assets/icon/account-wishlist-v2.svg' %}" alt="">
                    <p>المفضله</p>
                </a>
                </a>
                <hr>
                <a id="login-out" href="/">
                    <p> الصفحة الرئيسية </p>
                </a>
            </div>
            <div id="cart-orders">
                <div id="page-name">
                    <h1>Profile</h1>
                </div>
                <div class="container dark-grey-text mt-5 main-container">
                    <div class="row">
                        <div class="container ">
                            <div class="row mt-5">
                                <div class="profile-imgg col-md-12">
                                    {% if profile.image %}
                                    <img style="margin-bottom: 20px;border-radius: 50%;    height: 200px;
                                    width: 200px;" class="profile-img" src="{{profile.image.url}}" alt="card-img-top">
                                    {% else %}
                                    <img style="margin-bottom: 20px;border-radius: 50%;     height: 200px;
                                    width: 200px;" class="profile-img-defult" src="{% static 'img/user_no_image.png' %}"
                                        alt="card-img-top">
                                    {% endif %}
                                </div>
                                <div class="info mt-4 col-md-12">
                                    <h6><i class="fa-solid fa-signature"></i> الاسم : {{profile.user.first_name}}
                                        {{profile.user.last_name}} </h6>
                                    <h6><i class="fa-solid fa-envelope"></i> الايميل : {{profile.user.email}} </h6>
                                    <h6><i class="fa-solid fa-phone"></i> رقم التلفون : {{profile.phone}} </h6>
                                    <h6><i class="fa-solid fa-earth-americas"></i> الدوله :
                                        {{profile.country.name}} </h6>
                                    <h6><i class="fa-sharp fa-solid fa-city"></i> المدينه : {{profile.adress}} </h6>
                                    <a class="btn btn-outline-success-modify my-2 my-sm-0"
                                        href="{% url 'accounts:edit' slug=user.profile.slug%}">تعديل البروفايل</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</body>

</html>

accounts/templates/temp_actvation_account.html
{% autoescape off %}
    Hi {{ user.username }},
    Click <a href="{{ protocol }}://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}">here</a> to activate your account.
{% endautoescape %}