accounts/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='accounts'


urlpatterns = [
    path('signup',views.signup ,name='signup'),
    path('check_email_availability/', views.check_email_availability, name='check_email_availability'),
    path('signin',views.signin ,name='signin'),
    path('activate_account/<uidb64>/<token>/', views.activate_account, name='activate'),
    path('log_out',views.log_out ,name='log_out'),
    path('profile/<slug:slug>',views.profile ,name='profile'),
    path('profile/<slug:slug>/order',views.order ,name='order'),
    path('profile/<slug:slug>/order/<int:pk>/detail',views.order_details ,name='order_details'),
    path('productfavorites/<str:slug>',views.product_favorites ,name='product_favorites'),
    path('profile/<slug:slug>/product-favorites',views.showproduct_favorites ,name='showproduct_favorites'),
    path('profile/<slug:slug>/editprofile',views.edit_profile ,name='edit'),
]

orders/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import ajax_check_coupon
app_name='orders'


urlpatterns = [
    path('add_to_cart' , views.add_to_cart , name='add_to_cart'),
    path('cart' , views.cart , name='cart'),
    path('discount_value' , views.discount_value , name='discount_value'),
    path('ajax/check-coupon/', ajax_check_coupon, name='ajax_check_coupon'),
    path('remove_from_Cart/<int:orderdetials_id>' , views.remove_from_Cart , name='remove_from_Cart'),
    path('clear_Cart' , views.clear_Cart , name='clear_Cart'),
    path('add_qty/<int:orderdetials_id>' , views.add_qty , name='add_qty'),
    path('sub_qty/<int:orderdetials_id>' , views.sub_qty , name='sub_qty'),
    # path('payment' , views.ckeck_out , name='ckeck_out'),
    path('payment' , views.paypal_pament , name='paypal_pament'),
    path('order_completed' , views.order_completed , name='order_completed'),
]

product/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='product'


urlpatterns = [
    path('',views.product_list,name='product_list'),
    path('<str:slug>',views.product_detail,name='product_detail')
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('products.urls' ,namespace='products')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls' ,namespace='orders')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from audioop import reverse
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.utils.translation import gettext_lazy as _
from datetime import datetime
from django_countries.fields import CountryField
from django.utils.text import slugify
from django.db.models.signals import post_save
from products.models import Product
class Profile(models.Model):
    user=models.OneToOneField(User, verbose_name=_("user"), on_delete=models.CASCADE)
    productfavorites=models.ManyToManyField(Product,blank=True,null=True)
    phone=models.CharField(max_length=20,verbose_name=_("phone"))
    image=models.ImageField(upload_to='profile/',blank=True, null=True)
    country=CountryField(blank_label='select country')
    adress=models.CharField(max_length=100)
    join_date=models.DateTimeField(verbose_name=_("Created At"), default=datetime.now)
    slug=models.SlugField(blank=True, null=True) 
    
    def save(self ,*args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")

    def __str__(self):
        return '%s' %(self.user)

    def get_absolute_url(self):
        return reverse("accounts:Profile_detail", kwargs={"slug": self.slug})

    def create_profile(sender ,*args, **kwargs):
        if kwargs['created']:
            user_profile=Profile.objects.create(user=kwargs['instance'])    
    post_save.connect(create_profile , sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username' , 'email','first_name','last_name']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image' , 'country', 'adress']

accounts/views.py
from django.contrib import messages
from django.shortcuts import render ,redirect ,get_object_or_404
from orders.models import Order,OrderDetails
from.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login ,authenticate
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django_countries import countries
from.tokens import accout_actvation_token
from django.core.mail import EmailMessage
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes,force_str
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from project import settings
from django.contrib.auth import logout
from django.http import JsonResponse
from products.models import Product
def activate_account(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and accout_actvation_token.check_token(user, token):
        # activate the user's account
        user.is_active = True
        user.save()
        messages.success(request, 'Your account has been activated!')
        login(request, user)
        return redirect('/')
    else:
        messages.error(request, 'Invalid activation link.')
        return redirect('/')


def signup(request):
    if request.user.is_authenticated:  
        return redirect('/')
    
    if request.method == 'POST':
        first_name=None
        scand_name=None
        email=None
        password=None
        passwordconfigration=None
        
        if 'first_name' in request.POST : first_name=request.POST['first_name']
        else :messages.error(request,'Error in First Name !')
        
        if 'scand_name' in request.POST : scand_name=request.POST['scand_name']
        else :messages.error(request,'Error in Scand Name !')
        
        if 'email' in request.POST : email=request.POST['email']
        else : messages.error(request,'Error in Email !')
        
        if 'password' in request.POST: password=request.POST['password']
        else : messages.error(request,'Error in password !')
        
        if 'passwordconfigration' in request.POST: passwordconfigration=request.POST['passwordconfigration']
        else : messages.error(request,'Error in Password Configration !')
        
        context={'first_name':first_name,
                    'scand_name':scand_name,
                    'email':email}
        if first_name and scand_name and email and password and passwordconfigration:
            if User.objects.filter(email=email).exists():
                messages.error(request,'This Email Name is taken !')
                return render(request,'registration/signup.html',context)
            else:
                if password != passwordconfigration:
                    messages.error(request,'The two password fields didn’t match.')
                    return render(request,'registration/signup.html',context)
                else:
                    username = email.split("@")[0]
                    user = User.objects.create_user(
                    username=username,
                    first_name=first_name,
                    last_name=scand_name,
                    is_active=False,
                    email=email,
                    password=password
                    )
                    user.save()
        else:
            messages.error(request,'Please fill in all fields !')
            return render(request,'registration/signup.html',context)
        mailsubject='activate your account'
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = accout_actvation_token.make_token(user)
        message=f"Hi {user.username},\n\nPlease click on the following link to activate your account:\n\n{get_current_site(request).domain}/accounts/activate_account/{uid}/{token}/\n\nThanks!\n"
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [user.email,] 
        emailmessage=send_mail(mailsubject,message,email_from,recipient_list)
        
        if emailmessage:
            messages.success(request,f'User has been registered successfully , go to {email} to activate your account ! ')
            return redirect('/accounts/signin')
        else:
            messages.error(request,f'filed to send email to  {email} ! ')
            return redirect('/accounts/signup')
    else:
        return render(request,'registration/signup.html')

def check_email_availability(request):
    email = request.GET.get("email")
    response_data = {}
    if User.objects.filter(email=email).exists():
        response_data["available"] = False
    else:
        response_data["available"] = True
    return JsonResponse(response_data)

def signin(request):
    if request.user.is_authenticated:  
        return redirect('/')
    
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, 'Go to'+email+'to active your account !')
                return redirect('/accounts/signin')
        else:
            messages.error(request, 'Invalid email or password')
            return redirect('/accounts/signin')
    else:
        return render(request, 'registration/signin.html')

# def log_out(request):
#     context ={'log_out' : log_out}
#     return render(request, 'registration/logged_out.html',context)

def log_out(request):
    logout(request)
    return redirect('/')

@login_required(login_url='/accounts/login/')
def profile(request,slug):
    profile=get_object_or_404(Profile,slug=slug)
    if request.user.id == profile.user.id:
        context={'profile':profile}
        return render(request,'profile.html',context)
    else:
        return HttpResponseForbidden("You don't have permission to view this profile.")

@login_required(login_url='/accounts/login/')
def edit_profile(request ,slug):
    country_list = list(countries)
    if request.method == 'POST':
        if request.user is not None:
            user_profile = Profile.objects.get(user=request.user)
            context={
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
                'email': request.user.email,
                'phone': user_profile.phone,
                'country': user_profile.country,
                'country_list': country_list,
                'adress': user_profile.adress,
            }
            if request.POST['first_name'] and request.POST['last_name'] and request.POST['email'] and request.POST['phone'] and request.POST['country']  and request.POST['adress']:
                request.user.first_name= request.POST['first_name']
                request.user.last_name= request.POST['last_name']
                if request.POST['email'] != request.user.email:
                    if User.objects.filter(email=request.POST['email']).exists():
                        messages.error(request, 'Email is already taken.')
                        return render(request, 'editprofile.html', context)
                    request.user.email = request.POST['email']
                user_profile.phone= request.POST['phone']
                if 'country' in request.POST:
                    user_profile.country = request.POST['country']
                user_profile.adress= request.POST['adress']
                request.user.save()
                user_profile.save()
                messages.success(request,'Your Data Has Been Saved')
                context1={
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
                'email': request.user.email,
                'phone': user_profile.phone,
                'country': user_profile.country,
                'country_list': country_list,
                'adress': user_profile.adress,
                }
                slug = user_profile.slug
                return redirect ('/accounts/profile/' +slug+ '/editprofile')
            else:
                messages.error(request,'Please fill in all fields !')
                return render(request, 'editprofile.html',context)
        return render(request, 'editprofile.html',context)
    else:
        if request.user is not None:
            user_profile = Profile.objects.get(user=request.user)
            context={
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
                'email': request.user.email,
                'phone': user_profile.phone,
                'country': user_profile.country,
                'country_list': country_list,
                'adress': user_profile.adress,
            }
        return render(request, 'editprofile.html',context)
    
from operator import itemgetter
def order(request ,slug):
    profile=get_object_or_404(Profile,slug=slug)
    if request.user.id == profile.user.id:
        orders= Order.objects.all().filter(is_finished=True,user=request.user)
        sorted_orders = sorted(orders, key=lambda order: order.status == 'تم الشحن', reverse=True)
        context= {'sorted_orders' : sorted_orders ,}
        return render(request, 'about_me/orders.html',context)
    else:
        return HttpResponseForbidden("You don't have permission to view this profile.")

def order_details(request ,slug,pk):
    profile=get_object_or_404(Profile,slug=slug)
    if request.user.id == profile.user.id:

accounts/templates/about_me/favorite.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/about_me.css' %}">
    <title>Document</title>
</head>

<body dir="rtl">
    <div id="container">
        <nav id="nav"></nav>
        <main id="cart-orders-main">
            <div id="sitbar">
                <div id="person-name">
                    <h2> اهلا زياد احمد </h2>
                    <p>ziad0713@gmail.com</p>
                </div>
                <hr>
                <a class="icon-sitbar" href="{% url 'accounts:profile' slug=user.profile.slug %}">
                    <img src="{% static 'assets/icon/account-profile.svg' %}" alt="">
                    <p>حساب</p>
                </a>
                <a class="icon-sitbar" href="{% url 'accounts:order' slug=user.profile.slug %}">
                    <img src="{% static 'assets/icon/account-orders.svg' %}" alt="">
                    <p>الطلبات</p>
                </a>
                <a class="icon-sitbar" href="{% url 'accounts:showproduct_favorites' slug=user.profile.slug %}">
                    <img src="{% static 'assets/icon/account-wishlist-v2.svg' %}" alt="">
                    <p>المفضله</p>
                </a>
                <hr>
                <a id="login-out" href="/">
                    <p> الصفحة الرئيسية </p>
                </a>
            </div>
            <div id="theOrders">
                <div id="page-name">
                    <h1>تفاصيل الاوردر</h1>
                </div>
                {% for detail in order_details  %}
                    <div class="product-card">
                        <div class="name-order">
                            <h4>السعر {{detail.PRDCost}}</h4>
                            {% if detail.PRDNew %}
                                <p>منتج جديد</p>
                            {% endif %}
                        </div>
                        <hr>
                        <div class="text-product">
                            <a href="{% url 'products:product_detail' detail.slug %}" class="shipping" id="done">تفاصيل المنتج</a>
                            {% if detail.PRDIImage %}
                                <img style="opacity: 1;" src="{{ detail.PRDIImage.url }}" alt="#">
                            {% endif %}
                            <div>
                                <h4>{{detail.PRDname}}</h4>
                                <p>{{detail.PRDDesc}}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </main>
        <footer id="footer">

        </footer>
    </div>
</body>

</html>

accounts/templates/about_me/order_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/about_me.css' %}">
    <title>Document</title>
</head>

<body dir="rtl">
    <div id="container">
        <nav id="nav"></nav>
        <main id="cart-orders-main">
            <div id="sitbar">
                <div id="person-name">
                    <h2> اهلا زياد احمد </h2>
                    <p>ziad0713@gmail.com</p>
                </div>
                <hr>
                <a class="icon-sitbar" href="{% url 'accounts:profile' slug=user.profile.slug %}">
                    <img src="{% static 'assets/icon/account-profile.svg' %}" alt="">
                    <p>حساب</p>
                </a>
                <a class="icon-sitbar" href="{% url 'accounts:order' slug=user.profile.slug %}">
                    <img src="{% static 'assets/icon/account-orders.svg' %}" alt="">
                    <p>الطلبات</p>
                </a>
                <a class="icon-sitbar" href="#">
                    <img src="{% static 'assets/icon/account-wishlist-v2.svg' %}" alt="">
                    <p>المفضله</p>
                </a>
                <a class="icon-sitbar" href="#">
                    <img src="{% static 'assets/icon/cart.svg' %}" alt="">
                    <p>عربه التسوق</p>
                </a>
                <hr>
                <a id="login-out" href="#">
                    <p>تسجيل الخروج</p>
                </a>
            </div>
            <div id="theOrders">
                <div id="page-name">
                    <h1>تفاصيل الاوردر</h1>
                </div>
                {% for detail in order_details  %}
                    <div class="product-card">
                        <div class="name-order">
                            <h4>{{detail.order.status}}</h4>
                            <p>{{detail.order.order_date}}</p>
                        </div>
                        <hr>
                        <div class="text-product">
                            <a href="{% url 'products:product_detail' detail.product.slug %}" class="shipping" id="done">تفاصيل المنتج</a>
                            <img src="{{detail.product.PRDIImage.url}}" alt="#">
                            <div>
                                <h4>{{detail.product}}</h4>
                                <p>{{detail.product.PRDDesc}}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </main>
        <footer id="footer">

        </footer>
    </div>
</body>

</html>

accounts/templates/about_me/orders.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/about_me.css' %}">
    <title>Document</title>
</head>
<style>
    .a_detail {
        background: #0c1fff;
        color: wheat;
        width: 100px;
        padding: 10px;
        /* text-align: center; */
        /* align-items: center; */
        display: flex;
        justify-content: center;
        font-size: 17px;
        margin-top: 30px;
        border-radius: 20px;
    }
</style>
<body dir="rtl">
    <div id="container">
        <nav id="nav"></nav>
        <main id="cart-orders-main">
            <div id="sitbar">
                <div id="person-name">
                    <h2> اهلا زياد احمد </h2>
                    <p>ziad0713@gmail.com</p>
                </div>
                <hr>
                <a class="icon-sitbar" href="{% url 'accounts:profile' slug=user.profile.slug %}">
                    <img src="{% static 'assets/icon/account-profile.svg' %}" alt="">
                    <p>حساب</p>
                </a>
                <a class="icon-sitbar" href="{% url 'accounts:order' slug=user.profile.slug %}">
                    <img src="{% static 'assets/icon/account-orders.svg' %}" alt="">
                    <p>الطلبات</p>
                </a>
                <a class="icon-sitbar" href="{% url 'accounts:showproduct_favorites' slug=user.profile.slug %}">
                    <img src="{% static 'assets/icon/account-wishlist-v2.svg' %}" alt="">
                    <p>المفضله</p>
                </a>
                </a>
                <hr>
                <a id="login-out" href="/">
                    <p> الصفحة الرئيسية </p>
                </a>
            </div>
            <div id="theOrders">
                <div id="page-name">
                    <h1>الطلبات</h1>
                    <p>عرض سجل الطلبات الخاص بيك وتحقق من حالة التسليم للمنتجات</p>
                </div>
                {% for order in sorted_orders  %}
                    {% if order.status == 'تم الشحن' %}
                        <div class="product-card">
                            <div class="name-order">
                                <h4>{{order.id}}</h4>
                                <p>تم الطلب يوم  {{order.order_date}}</p>
                                <a class="a_detail" href="{% url 'accounts:order_details' slug=user.profile.slug pk=order.id %}">تفاصيل الطلب</a>
                            </div>
                            <hr>
                            <div class="text-product" style="    margin-right: auto;">
                                <div class="shipping" id="done">{{order.status}}</div>
                                <a class="navbar-brand" href="/"><img src="/static/assets/icon/amd2.svg" alt=""> logo</a>
                            </div>
                        </div>
                    {% else %}
                        <div class="product-card">
                            <div class="name-order">
                                <h4>{{order.id}}</h4>
                                <p>تم الطلب يوم  {{order.order_date}}</p>
                                <a class="a_detail" href="{% url 'accounts:order_details' slug=user.profile.slug pk=order.id %}">تفاصيل الطلب</a>
                            </div>
                            <hr>
                            <div class="text-product" style="    margin-right: auto;">
                                <div class="shipping" id="load">{{order.status}}</div>
                                <a class="navbar-brand" href="/"><img src="/static/assets/icon/amd2.svg" alt=""> logo</a>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </main>
        <footer id="footer">

        </footer>
    </div>
</body>

</html>